### PR TITLE
Added standalone restart script for accidental host reboot/shutdown

### PR DESCRIPTION
**Pull request by anandadfoxx**
I had used several months ago for our education environment, and we felt a problem when do restoring all container after an host accidental shutdown (e.g. power outage) to the working state.

To resolve this specific case, I just created a new standalone shell script that located in `platform/utils/save_and_restore/restart_mini_internet.sh` that will performs these mechanisms below:

1. The script will use all backuped configurations that compressed as `.tar.gz` archive in the `students_config` directory with the format should be `configs-as-<as number>.tar.gz`  
Correct example of
2. Script will perform hard cleanup, by executing `./cleanup/clean.up` and ` ./cleanup/hard_reset.sh`
3. Script will perform the startup the project, executing `./startup.sh`, then `./utils/ssh/portforwarding.sh`, and finally `./utils/iptables/filters.sh`, and unpausing the MATRIX container, and show the new AS SSH login password (due to perform startup.sh again).
4. Script will perform config restoration which are based on config defined at point 1, the script is able to store router's FRR config, end-host such as server configuration with IPv4, IPv6, and also able to restore the switch configuration (VLAN etc.). The full usage of the configuration will being described later.

The usage of the `restart_mini_internet.sh` described at the `-h` flag, that explained below image.
Script usage documentation

Considerations when using this script:
- When do a backup, the script **WILL WIPES ALL THE FILES CONTAINED IN THE `students_config` to overwrite with the new configuration, so please move your backuped config in the another location**
- To perform restore, please make sure the format is same as the point 1 describes.
- Currently, this script isn't able to store regarding RPKI configurations such as Krill.

**NOTES FOR THE PULL REQUEST**
Please try first into your environment, and merge with squashed merge to simplify the commit. Thank you for the considerations.

Regards,
anandadfoxx

### CODE REVIEW

**Comment by NotSpecial** [comment]
Hi, thank you for your contribution.

I think that the `restore_configuration` function in itself would be very helpful. Could you please provide this separately as well, ideally with a command line argument to only restore a specified group?

(You could still call it from your current restart script)

Thank you!

**Comment by anandadfoxx** [comment]
Okay, thank you for the suggestion!

I have commited an changes mentioned in your suggestions within the interactivity of the script. Now the `reset_with_startup` and `restore_configs` are separated with their respective option flags, and also added an option to specify AS group that will involves the execution of the script.

**Comment by anandadfoxx** [comment]
Okay, thank you for the suggestion!

I have commited an changes mentioned in your suggestions within the interactivity of the script. Now the `reset_with_startup` and `restore_configs` are separated with their respective option flags, and also added an option to specify AS group that will involves the execution of the script.
Example of reset and restore for AS 3,13

I had also add the visibility of the help for CAUTION sections.
New script usage

Here are some brief changes:
- `reset_with_startup` now separated as `-s` flag
- `restore_configs` now separated as `-r` flag
- Added new `-g` flag to specify AS groups that involves the backup/restore
- Added visibility for CAUTION sections
- Fixed another working directory not working

**Comment by NotSpecial** [comment]
Hi, and first of all thank you for your patience. The last months have been quite busy for me and I couldn't get back to this.

I've just merged some big changes we did to the project under the hood earlier this year to improve performance.

Technically, I believe this should not affect any of your work, but could you perhaps test whether your changes still work with the updated Mini-Internet? If they do, I'm happy to merge.

Cheers,
Alex

**Pull request merged**
